# Use the apache/hive:4.0.0 image as the base
FROM apache/hive:4.0.0

# Update the package list and install iputils-ping (for ping) and telnet
RUN apt - get update && \
    apt - get install - y iputils - ping telnet
